# k create configmap  db-config-vol --from-literal=DB_USER=backend -n chapter3
# k create configmap db-config --from-literal=DB_HOST=mysql-service -n chapter3

# k create secret generic secret-basic --from-literal=pwd=test -n chapter3
# k create secret generic secret-ssh-auth  --from-file=ssh-privatekey --type=kubernetes.io/ssh-auth -n chapter3


apiVersion: v1
kind: Pod
metadata: 
  name: config-secrete-env
spec:
  containers:
  - name: memcached
    image: memcached:1.6.8
    env:
    - name:  MYSQL_USER
      value:  "root"
    envFrom:
    - configMapRef:
        name: db-config
    - secretRef:
        name: secret-basic
    volumeMounts:
    - name: db-config-vol
      mountPath: /etc/config
    - name: ssh-vol
      mountPath: /var/app
      readOnly: true


  volumes:
  - name: db-config-vol
    configMap:
      name: db-config-vol
  - name: ssh-vol
    secret:
      secretName: secret-ssh-auth