apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: aap-cache
spec:
  maxReplicas: 5
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app-cache
  targetCPUUtilizationPercentage: 80
