apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: chapter3
  labels:
    app: redis
spec:
  ports:
  - port: 6379
    protocol: TCP
  selector:
    app: redis
  type: CLusterIP
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefullSet
metadata:
  name: redis
  namespace: chapter3
spec:
  selector:
    matchLabels:
      app: redis
    replicas: 1
    serviceName: redis
    template:
      metadata:
        labels:
          app: redis
      spec:
        containers:
        - name: redis
          image: redis:6.2.5
          command: ["redis-server", "--appendonly", "yes"]
          ports:
          - containerPort: 6379
            name: web
          volumenMounts:
          - name: redis-vol
            mountPath: /data
volumeClaimTemplates:
- metadata:
    name: redis-vol
  spec:
    accessModes: ["ReadWriteOnce"]
    resources:
      requests:
        storage: 1Gi