apiVersion: v1
kind: Pod
metadata:
  name: args-pod
spec:
  containers:
  - image: luksa/fortune:args
    args: ["2"]
    name: args-container
    volumeMounts:
    - name: html
      mountPath: /var/htdocs
  volumes:
  - name: html
    emptyDir: {}
    