apiVersion: v1
kind: Pod
metadata:
  name: pod-cm
spec:
  containers:
  - image: luksa/fortune:env
    name: cont-env-cm
    env:
    - name: INTERVAL
      valueFrom:
        configMapKeyRef:
          name: second-config
          key: sleep-interval