apiVersion: batch/v1
kind: Job
metadata:
  name: first-job
  labels:
    env: test
spec:
  completion: 5
  parallelism: 2
  template:
    metadata:
      labels:
        app: test-job

    spec:
      restartPolicy: OnFailure
      containers:
      - name: cont-job
        image: luksa/batch-job
