apiVersion: v1
kind: Service
metadata:
  name: headless-service
spec:
  clusterIP: None
  ports:

  - port: 80
    targetPort: 8080
    name: http

  - port: 443
    targetPort: 8443
    name: https
  selector:
    app: prod