apiVersion: v1
kind: Pod
metadata: 
  name: normal-volume
spec:
  volumes:
  - name: mongo-data
    hostPath:
      path: "/db"
  containers:
    - image: mongo
      name: mongodb
      volumeMounts:
      - name: mongo-data
        mountPath: /data/db
    ports:
    - cotainerPort: 27017
      protocal: TCP

  
