apiVersion: v1
kind: Pod
metadata:
  name: pod-pvc
spec:
  containers:
  - image: mongo
    name: mongodb
    volumeMounts:
    - name: mongo-data
      mountPath: /data/db
    ports:
    - containerPort: 27017
      protocol: TCP
  volumes:
  - name: mongo-data
    persistentVolumeClaim:
      claimName: mongo-pvc