apiVersion: v1
kind: Pod
metadata: 
  name: pod-liveness
spec:
  containers:
  - image: luksa/kubia-unhealthy
    name: pod-unhealthy
    livenessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 15