apiVersion: apps/v1
kind: DeamonSet
metadata:
  name: first-ds
  labels:
    env: prod
spec:
  replicas: 2
  selector:
    matchlabels:
      env: prod
  template:
    metadata:
      labels:
        env: prod
    spec:
      nodeSelector:
        gpu: "true"
      containers:
      - image: luksa/kubia
        name: pod-first
        ports:
        - containerPort: 8080
          protocol: TCP
